global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'ls_app'
    static_configs:
      - targets: [ 'ls.dev.hyvee.de:443' ]
    scheme: https
    tls_config:
        insecure_skip_verify: true
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus